### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 522726: illegal multibyte sequence

### ISSUE THREAD

**Issue by vjclions** [madpah/vexy#13]
Hi,

We encountered this issue when used VEXY to create VEX document for a SBOM, in CycloneDX format, generated by a commercial SBOM tool. The VEXY error message is: 

Vexy is configured to use 2 data sources. 
Parsing CycloneDX BOM for Components ----------------------------------------   0% -:--:--
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Program Files\Python311\Scripts\vexy.exe\__main__.py", line 7, in <module>
  File "D:\Program Files\Python311\Lib\site-packages\vexy\client.py", line 298, in main
    VexyCmd(args).execute()
  File "D:\Program Files\Python311\Lib\site-packages\vexy\client.py", line 159, in execute
    input_bom = Bom.from_json(data=json.loads(input_bom_fh.read()))  # type: ignore[attr-defined]
[sbom_2023-03-02_102402.cdx.zip](https://github.com/madpah/vexy/files/10915569/sbom_2023-03-02_102402.cdx.zip)

                                              ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9d in position 522726: illegal multibyte sequence
 
I have attached a copy of the SBOM file. 

Thanks

Vincent Chu

**Comment by vjclions** [comment]
We solved and closed the issue. 

Vincent Chu
